include: package:flutter_lints/flutter.yaml

linter:
  rules:

    avoid_print: false

    prefer_single_quotes: false

    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    prefer_constructors_over_static_methods: false